run_id: '002'

model:
  type: 'faster_rcnn'
  id: '01'  # frozen
  pretrained_on: 'custom'

  backbone:
    type: 'resnet50_v1b' #'mobilenet1.0'
    n_layers: 50

data:
  root_dir: 'data/filtered/'
  name: 'cycle'
  split_id: '001'


train:

  epochs: 40
  lr_decay_epochs: [14,20]

  lr_warmup: -1  # voc -1, coco -1 for 1 gpu, 8000/#gpus

  weight_decay: 0.0005  # voc 0.0005, coco 0.0001 # Weight decay, for regularization
#
#val:
#  every: 100 #0  # run validation every x epochs
#
#vis:
#  every: 1000  # update tensorboard every x steps (minibatches)